//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanilaBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauBep
    {
        public int MaDB { get; set; }
        public string TenDauBep { get; set; }
        public string HinhAnh { get; set; }
        public string ChucDanh { get; set; }
        public string CauChamNgon { get; set; }
    }
}
